Use magisk tools now

diff --git a/META-INF/com/google/android/updater-script b/META-INF/com/google/android/updater-script
--- a/META-INF/com/google/android/updater-script
+++ b/META-INF/com/google/android/updater-script
@@ -1,1 +1,101 @@
-# Dummy file; update-binary is a shell script.
+#MAGISK
+##########################################################################################
+#
+# Magisk Flash Script
+# by topjohnwu
+#
+# This script will detect, construct the environment for Magisk
+# It will then call boot_patch.sh to patch the boot image
+#
+##########################################################################################
+
+##########################################################################################
+# Preparation
+##########################################################################################
+
+COMMONDIR=$INSTALLER/common
+APK=$COMMONDIR/magisk.apk
+CHROMEDIR=$INSTALLER/chromeos
+
+# Default permissions
+umask 022
+
+OUTFD=$2
+ZIP=$3
+
+if [ ! -f $COMMONDIR/util_functions.sh ]; then
+  echo "! Unable to extract zip file!"
+  exit 1
+fi
+
+# Load utility fuctions
+. $COMMONDIR/util_functions.sh
+
+setup_flashable
+
+##########################################################################################
+# Detection
+##########################################################################################
+
+ui_print "***************************"
+ui_print "* Kernel Sepolicy Patcher *"
+ui_print "*      By: Zackptg5       *"
+ui_print "***************************"
+
+is_mounted /data || mount /data || is_mounted /cache || mount /cache || abort "! Unable to mount partitions"
+mount_partitions
+
+find_boot_image
+
+[ -z $BOOTIMAGE ] && abort "! Unable to detect target image"
+ui_print "- Target image: $BOOTIMAGE"
+
+# Detect version and architecture
+api_level_arch_detect
+
+BINDIR=$INSTALLER/$ARCH32
+chmod -R 755 $CHROMEDIR $BINDIR
+
+##########################################################################################
+# Environment
+##########################################################################################
+
+MAGISKBIN=$INSTALLER/bin
+mkdir -p $MAGISKBIN 2>/dev/null
+cp -af $BINDIR/. $COMMONDIR/. $CHROMEDIR $BBDIR/busybox $MAGISKBIN
+chmod -R 755 $MAGISKBIN
+
+$BOOTMODE || recovery_actions
+
+##########################################################################################
+# Boot patching
+##########################################################################################
+
+eval $BOOTSIGNER -verify < $BOOTIMAGE && BOOTSIGNED=true
+$BOOTSIGNED && ui_print "- Boot image is signed with AVB 1.0"
+
+SOURCEDMODE=true
+cd $MAGISKBIN
+
+# Source the boot patcher
+. ./boot_patch.sh "$BOOTIMAGE"
+
+ui_print "- Flashing new boot image"
+
+if ! flash_image new-boot.img "$BOOTIMAGE"; then
+  ui_print "- Compressing ramdisk to fit in partition"
+  ./magiskboot cpio ramdisk.cpio compress
+  ./magiskboot repack "$BOOTIMAGE"
+  flash_image new-boot.img "$BOOTIMAGE" || abort "! Insufficient partition size"
+fi
+
+./magiskboot cleanup
+rm -f new-boot.img
+
+cd /
+# Cleanups
+$BOOTMODE || recovery_cleanup
+rm -rf $TMPDIR
+
+ui_print "- Done"
+exit 0
